### ISSUE TITLE
Missing Compass ReadingChanged event handler

### ISSUE THREAD

**Issue by dlbroadfoot** [rdavisau/essential-interfaces#4]
Hi Ryan,

It appears the ICompass interface is missing the event `EventHandler<CompassChangedEventArgs> ReadingChanged`

Would it be possible to add this in?

Thanks,

David

**Comment by rdavisau** [comment]
👀 So it is.. thanks for letting me know! I'll take a look.

**Comment by rdavisau** [comment]
Thanks for reporting this. It seems we were missing a certain kind of event definition when generating the models. `ReadingChanged` for `ICompass` (and friends) is available as of 1.3.1.1 🆒 

![image](https://user-images.githubusercontent.com/7392704/65809692-84011500-e1e3-11e9-9226-1a478008b2e8.png)
