### ISSUE TITLE
1.7.1 Release

### ISSUE THREAD

**Issue by Axemasta** [rdavisau/essential-interfaces#8]
You're probably aware but can we have a public release for the new version of [Xamarin.Essentials (1.7.1)](https://github.com/xamarin/Essentials/releases/tag/1.7.1)? 😁

**Comment by rdavisau** [comment]
Should be available [shortly](https://www.nuget.org/packages/Xamarin.Essentials.Interfaces/1.7.1) 🙂 - thanks for the bump.
