### ISSUE TITLE
Release 1.7.7

### ISSUE THREAD

**Issue by antoine-hebert** [rdavisau/essential-interfaces#9]
Hello there @rdavisau ! 

Would be great to have the latest stable release version available : [Xamarin.Essentials (1.7.7)](https://github.com/xamarin/Essentials/releases/tag/1.7.7) :)

**Comment by rdavisau** [comment]
Hello, thanks for the bump - it's available now https://www.nuget.org/packages/Xamarin.Essentials.Interfaces/1.7.7 🚀
